name: test
on:
  pull_request: { branches: ['*'] }
  push: { branches: ['main'] }

env:
  LOG_LEVEL: debug
  SWIFT_DETERMINISTIC_HASHING: 1
  REDIS_HOSTNAME: redis

jobs:
  api-breakage:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    container: swift:5.7-jammy
    steps:
      - name: Check out package
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # https://github.com/actions/checkout/issues/766
      - name: Mark the workspace as safe
        run: git config --global --add safe.directory ${GITHUB_WORKSPACE}
      - name: Check for API breaking changes
        run: swift package diagnose-api-breaking-changes origin/main

  linux-unit:
    strategy:
      fail-fast: false
      matrix:
        container:
          - swift:5.5-bionic
          - swift:5.6-focal
          - swift:5.7-jammy
    container: ${{ matrix.container }}
    services:
      redis:
        image: redis:6
        ports: ["6379:6379"]
    runs-on: ubuntu-latest
    steps:
      - name: Check out package
        uses: actions/checkout@v3
      - name: Run unit tests with Thread Sanitizer
        run: swift test --sanitize=thread
  
  # TODO: Use reusable workflow
