name: test
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request: { types: [opened, reopened, synchronize, ready_for_review] }
  push: { branches: [ main ] }

env:
  LOG_LEVEL: info
  SWIFT_DETERMINISTIC_HASHING: 1
  REDIS_HOSTNAME: redis

jobs:
  api-breakage:
    if: ${{ !(github.event.pull_request.draft || false) }}
    runs-on: ubuntu-latest
    container: swift:5.10-jammy
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with: { 'fetch-depth': 0 }
      - name: Run API breakage check
        run: |
          git config --global --add safe.directory "${GITHUB_WORKSPACE}"
          swift package ${PACKAGE_ROOT} diagnose-api-breaking-changes origin/main

  linux-unit:
    if: ${{ !(github.event.pull_request.draft || false) }}
    strategy:
      fail-fast: false
      matrix:
        container:
          - swift:5.8-jammy
          - swift:5.9-jammy
          - swift:5.10-noble
          - swift:6.0-noble
          - swiftlang/swift:nightly-main-jammy
        redis:
          - redis:6
          - redis:7
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    services:
      redis:
        image: ${{ matrix.redis }}
        ports: ["6379:6379"]
    steps:
      - name: Check out package
        uses: actions/checkout@v4
      - name: Run unit tests with Thread Sanitizer and coverage
        run: swift test --sanitize=thread --enable-code-coverage
      - name: Submit coverage report to Codecov.io
        uses: vapor/swift-codecov-action@v0.3
        with:
          codecov_token: ${{ secrets.CODECOV_TOKEN || '' }}
